# Common system setup tasks
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install essential packages
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - htop
      - vim
      - tree
      - jq
    state: present
  become: yes

- name: Install AWS CLI v2
  block:
    - name: Download AWS CLI v2
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Unzip AWS CLI
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install"
      become: yes
      args:
        creates: "/usr/local/bin/aws"

    - name: Clean up AWS CLI installation files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/awscliv2.zip"
        - "/tmp/aws"

- name: Install kubectl
  block:
    - name: Get latest kubectl version
      uri:
        url: "https://dl.k8s.io/release/stable.txt"
        return_content: yes
      register: kubectl_version

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"
        dest: "/tmp/kubectl"
        mode: '0755'

    - name: Install kubectl
      copy:
        src: "/tmp/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'
        remote_src: yes
      become: yes

    - name: Clean up kubectl download
      file:
        path: "/tmp/kubectl"
        state: absent

- name: Create homelab directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - "/home/ubuntu/homelab"
    - "/home/ubuntu/backups"
    - "/home/ubuntu/.kube"

- name: Set timezone to UTC
  timezone:
    name: UTC
  become: yes