# applications/kubernetes/manifests/01-secret-store/secret-store.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: homelab
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Uses the EC2 instance IAM role - no explicit credentials needed
