# infrastructure/ansible/roles/docker/tasks/main.yml
# Docker and Docker Compose installation

- name: Install Docker prerequisites
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - apt-transport-https
    state: present
  become: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Update package cache after adding Docker repo
  apt:
    update_cache: yes
  become: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes

- name: Reconnect to apply group changes
  meta: reset_connection

- name: Create Docker daemon configuration
  copy:
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2"
      }
    dest: /etc/docker/daemon.json
    mode: '0644'
  become: yes
  notify: restart docker

- name: Restart Docker to apply configuration
  systemd:
    name: docker
    state: restarted
  become: yes

# Verification
- name: Wait for Docker to be ready
  pause:
    seconds: 10

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version
  changed_when: false

- name: Test Docker functionality
  command: docker run --rm hello-world
  register: docker_test
  changed_when: false

- name: Display Docker setup completion
  debug:
    msg:
      - "✅ Docker setup complete"
      - "Docker version: {{ docker_version.stdout }}"
      - "Docker Compose version: {{ compose_version.stdout }}"
      - "Docker test: {{ 'PASSED' if docker_test.rc == 0 else 'FAILED' }}"