# Alternative approach - using service account (cleaner)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: homelab
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # This uses the pod's service account with IAM role
      # No explicit credentials needed!