apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: homelab
data:
  Caddyfile: |
    {
        email admin@avigdol.com
        
        # Use staging ACME for testing (switch to production later)
        acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
        
        # Production ACME (comment out staging above and uncomment this when ready)
        # acme_ca https://acme-v02.api.letsencrypt.org/directory
        
        admin 0.0.0.0:2019
        
        log {
            level INFO
            output stdout
        }
    }

    # Vaultwarden - Password Manager
    passwords.avigdol.com {
        reverse_proxy vaultwarden:80
        
        @websockets {
            header Connection *Upgrade*
            header Upgrade websocket
        }
        reverse_proxy @websockets vaultwarden:3012
        
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options DENY
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
            Referrer-Policy same-origin
        }
    }

    # Nextcloud - File Sync
    files.avigdol.com {
        reverse_proxy nextcloud:80
        
        redir /.well-known/carddav /remote.php/dav permanent
        redir /.well-known/caldav /remote.php/dav permanent
        
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options SAMEORIGIN
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
            Referrer-Policy same-origin
            -Server
        }
        
        request_body {
            max_size 512MB
        }
    }

    # Jenkins - CI/CD
    jenkins.avigdol.com {
        reverse_proxy jenkins:8080
        
        header {
            Strict-Transport-Security max-age=31536000;
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
        }
    }

    # Grafana - Monitoring Dashboard
    monitor.avigdol.com {
        reverse_proxy grafana:3000
        
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options SAMEORIGIN
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
        }
    }