apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: homelab
data:
  Caddyfile: |
    {
        email admin@avigdol.com
        
        # Use Let's Encrypt staging environment
        acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
        
        admin 0.0.0.0:2019
        log {
            level INFO
            output stdout
        }
    }

    passwords.avigdol.com {
        reverse_proxy vaultwarden:80
        
        @websockets {
            header Connection *Upgrade*
            header Upgrade websocket
        }
        reverse_proxy @websockets vaultwarden:3012
        
        tls {
            dns route53 {
                region us-east-1
            }
        }
    }

    files.avigdol.com {
        reverse_proxy nextcloud:80
        
        tls {
            dns route53 {
                region us-east-1
            }
        }
        
        redir /.well-known/carddav /remote.php/dav permanent
        redir /.well-known/caldav /remote.php/dav permanent
        
        request_body {
            max_size 512MB
        }
    }

    jenkins.avigdol.com {
        reverse_proxy jenkins:8080
        
        tls {
            dns route53 {
                region us-east-1
            }
        }
    }

    monitor.avigdol.com {
        reverse_proxy grafana:3000
        
        tls {
            dns route53 {
                region us-east-1
            }
        }
    }