apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: homelab
data:
  Caddyfile: |
    {
        email admin@avigdol.com
        # PRODUCTION ACME
        acme_ca https://acme-v02.api.letsencrypt.org/directory
        # For testing:
        # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
        # (No acme_dns block -> HTTP-01 will be used)
    }

    passwords.avigdol.com {
        reverse_proxy vaultwarden.homelab.svc.cluster.local:80
        @websockets {
            header Connection *Upgrade*
            header Upgrade websocket
        }
        reverse_proxy @websockets vaultwarden.homelab.svc.cluster.local:3012
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options DENY
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
            Referrer-Policy same-origin
        }
    }

    files.avigdol.com {
        reverse_proxy nextcloud.homelab.svc.cluster.local:80
        redir /.well-known/carddav /remote.php/dav permanent
        redir /.well-known/caldav /remote.php/dav permanent
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options SAMEORIGIN
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
            Referrer-Policy same-origin
            -Server
        }
        request_body {
            max_size 512MB
        }
    }

    jenkins.avigdol.com {
        reverse_proxy jenkins.homelab.svc.cluster.local:8080
        header {
            Strict-Transport-Security max-age=31536000;
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
        }
    }

    monitor.avigdol.com {
        reverse_proxy grafana.homelab.svc.cluster.local:3000
        header {
            Strict-Transport-Security max-age=31536000;
            X-Frame-Options SAMEORIGIN
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options nosniff
        }
    }
