apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: homelab
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.8.4-alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 2019
          name: admin
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
          readOnly: true
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        livenessProbe:
            httpGet:
              path: /
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 30
        readinessProbe:
            httpGet:
              path: /
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-data
      - name: caddy-config
        persistentVolumeClaim:
          claimName: caddy-config
