apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: homelab
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        # Keep your Route53 image
        image: caddy:2.8.4-alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 2019
          name: admin
        env:
        - name: AWS_REGION
          value: "us-east-1"
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
          readOnly: true
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        # FIXED: Health checks that work with Caddy admin API
        livenessProbe:
          httpGet:
            path: /config/
            port: 2019
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /config/
            port: 2019
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      - name: caddy-data
        persistentVolumeClaim:
          claimName: caddy-data
      - name: caddy-config
        persistentVolumeClaim:
          claimName: caddy-config