apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: homelab
  labels:
    app: caddy
spec:
  type: NodePort
  selector:
    app: caddy
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
  - name: admin
    port: 2019
    targetPort: 2019
    nodePort: 30019