db_address: "vaultwarden-db.clg6aey28a96.eu-central-1.rds.amazonaws.com"
db_name: "vaultwarden"
db_password: "DXSbJ8Ezy8+Cksu4lyHv"
db_username: "vwuser"
subnet_id: "subnet-0488a1d2dff09317c"
vaultwarden_backup_bucket_name: "homelab-874888505976"
vaultwarden_backup_bucket_prefix: "vaultwarden/"
vaultwarden_instance_profile_name: "vaultwarden-instance-profile"
vaultwarden_sg_id: "sg-074244e8be0f19f22"
