# applications/kubernetes/manifests/05-grafana/configmap-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: homelab
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.homelab.svc.cluster.local:9090
        isDefault: true
        editable: true
