# applications/kubernetes/manifests/05-grafana/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: homelab
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000