# applications/kubernetes/manifests/06-jenkins/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: homelab
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: agent
    port: 50000
    targetPort: 50000