# K3s installation (for future Kubernetes learning)
- name: Check if K3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
  become: yes
  when: not k3s_installed.stat.exists

- name: Enable K3s service
  systemd:
    name: k3s
    enabled: yes
    state: started
  become: yes

- name: Wait for K3s to be ready
  wait_for:
    port: 6443
    host: localhost
    delay: 10
    timeout: 60
  when: not k3s_installed.stat.exists

- name: Copy K3s kubeconfig for ubuntu user
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  become: yes

- name: Test K3s installation
  command: kubectl get nodes
  register: k3s_nodes
  become_user: ubuntu
  changed_when: false

- name: Display K3s status
  debug:
    msg: "K3s nodes: {{ k3s_nodes.stdout_lines }}"