# applications/kubernetes/manifests/05-nextcloud/nextcloud-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: homelab
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:28.0.2-apache
        ports:
        - containerPort: 80
        env:
        - name: NEXTCLOUD_ADMIN_USER
          value: "admin"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-admin
              key: NEXTCLOUD_ADMIN_PASS
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "files.avigdol.com"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: OVERWRITEHOST
          value: "files.avigdol.com"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: REDIS_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: DB_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db
              key: DB_PASSWORD
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        - name: nextcloud-apps
          mountPath: /var/www/html/custom_apps
        - name: nextcloud-config
          mountPath: /var/www/html/config
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /status.php
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data
      - name: nextcloud-apps
        persistentVolumeClaim:
          claimName: nextcloud-apps
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nextcloud-config
