- name: Install required apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Create Vaultwarden app folder
  file:
    path: /opt/vaultwarden
    state: directory

- name: Template Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/vaultwarden/docker-compose.yml
    mode: '0644'

- name: Start Vaultwarden with Docker Compose
  shell: docker compose up -d
  args:
    chdir: /opt/vaultwarden
