- name: restart mailserver
  community.docker.docker_compose_v2:
    project_src: "/home/ubuntu/homelab/docker-compose/mailserver"
    files: ["docker-compose.mail.yml"]
    state: present
    restarted: true
