# infrastructure/ansible/roles/applications/tasks/main.yml
# Smart role that deploys Docker Compose OR Kubernetes

- name: Display deployment mode
  debug:
    msg: "🚀 Deploying applications in {{ deployment_mode | default('docker') }} mode"

- name: Create application directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - "/home/ubuntu/homelab"
    - "/home/ubuntu/homelab/docker-compose"
    - "/home/ubuntu/homelab/kubernetes"

- name: Copy all application files
  copy:
    src: "{{ playbook_dir }}/../../../applications/"
    dest: "/home/ubuntu/homelab/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
    directory_mode: '0755'

- name: Set executable permissions
  file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - "/home/ubuntu/homelab/docker-compose/generate-secrets.sh"
    - "/home/ubuntu/homelab/docker-compose/deploy.sh"
  ignore_errors: yes

- name: Install management scripts
  template:
    src: homelab-script.j2
    dest: /usr/local/bin/homelab
    mode: '0755'
  become: yes

# Deploy based on mode
- include_tasks: docker-deploy.yml
  when: deployment_mode | default('docker') == 'docker'

- include_tasks: k8s-deploy.yml  
  when: deployment_mode | default('docker') == 'k8s'