apiVersion: v2
name: grafana
description: Grafana monitoring dashboard (using official chart)
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: "8.5.2"
    repository: "https://grafana.github.io/helm-charts"
