grafana:
  # Admin password from secret created by Ansible (FIXED KEYS)
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  
  # Database configuration using ExternalSecret
  env:
    GF_USERS_ALLOW_SIGN_UP: "false"
    GF_SERVER_ROOT_URL: "https://monitor.avigdol.com"
    GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-worldmap-panel"
    GF_DATABASE_TYPE: "postgres"
  
  # Database credentials from ExternalSecret
  envFromSecret: grafana-db-secret

  persistence:
    enabled: true
    size: 1Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL for now
    hosts:
      - monitor.avigdol.com
    tls: []  # Disable TLS for now

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus:9090
          access: proxy
          isDefault: true

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi