- name: Wait for cloud-init to finish
  wait_for:
    path: /var/lib/cloud/instance/boot-finished
    timeout: 300
  become: yes

- name: Kill any hanging apt processes
  shell: killall apt-get || true
  become: yes
  ignore_errors: yes

- name: Install essential packages
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - jq
      - htop
      - vim
      - tree
      - python3-pip
      - python3-boto3
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  
- name: Install AWS CLI v2
  block:
    - name: Download AWS CLI v2
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install --update"
      become: yes
      args:
        creates: "/usr/local/bin/aws"

    - name: Clean up AWS CLI files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/awscliv2.zip"
        - "/tmp/aws"

- name: Create homelab directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  loop:
    - "/home/ubuntu/homelab"
    - "/home/ubuntu/backups"

- name: Set timezone to UTC
  timezone:
    name: UTC
  become: yes