name: Terraform Plan

on:
  pull_request:
    branches: [ main ]
    paths: [ 'infrastructure/terraform/**' ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: infrastructure/terraform/environments/dev
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Terraform Plan
      run: terraform plan -no-color
      env:
        TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
        TF_VAR_s3_bucket_name: ${{ secrets.TF_VAR_s3_bucket_name }}
        TF_VAR_allowed_cidr_blocks: ${{ secrets.TF_VAR_allowed_cidr_blocks }}
