name: Terraform Plan

on:
  pull_request:
    branches: [ main ]
    paths: [ 'infrastructure/terraform/**' ]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      run: terraform init
      working-directory: infrastructure/terraform/environments/dev
    
    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: infrastructure/terraform/environments/dev