# applications/kubernetes/manifests/04-prometheus/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: homelab
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093

    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Node Exporter - System Metrics
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.homelab.svc.cluster.local:9100']
        scrape_interval: 30s
        metrics_path: /metrics

      # cAdvisor - Container metrics (built into kubelet)
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      # Vaultwarden (if it exposes metrics)
      - job_name: 'vaultwarden'
        static_configs:
          - targets: ['vaultwarden.homelab.svc.cluster.local:80']
        metrics_path: /metrics
        scrape_interval: 60s
        scrape_timeout: 10s

      # Nextcloud (if it exposes metrics)
      - job_name: 'nextcloud'
        static_configs:
          - targets: ['nextcloud.homelab.svc.cluster.local:80']
        metrics_path: /metrics
        scrape_interval: 60s
        scrape_timeout: 10s